version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: linkboard_db
      POSTGRES_USER: linkboard_user
      POSTGRES_PASSWORD: linkboard_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
